var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                 <              ",
   "                                                                                ",
   "                                          xxx                               o   ",
   "          v   G    ooooooo             <                                    <  o",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "        o     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  @           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                     xxx                                                        ",
   "                     xxx                                                     x  ",
   "  xx                                                                    <    x  ",
   "  x                             <                                            x  ",
   "  x              o                                    <                    o x  ",
   "  x          xx                          o                                   x  ",
   "  x  @                   <  o     o     o o                    < xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                            x!!!!!x                  x     x                    ",
   "                            x!!!!!x                  x!!!!!x                    ",
   "                            x!!!!!x                  x!!!!!x                    ",
   "                            xxxxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                            oo                                  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                         x!!!!!!x                               ",
   "                                    o    x!!!!!!x                               ",
   "                                   xxx   x!!!!!!x                               ",
   "                                         x!!!!!!x                               ",
   "                                         x!!!!!!x                               ",
   "                                    o    x!!!!!!x                               ",
   "        v                          xxx   x!!!!!!x                               ",
   "                               <         x!!!!!!!x                              ",
   "  xx            ooooooo               <  x!!!!!!!!x                             ",
   "                                      <  x!!!!!!!!x         o              W    ",
   "  @  G!                                xxxx!!!!!!!!x                            ",
   "xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                  x     x   x   xx    x                                         ",
   "                  x     x   x   x x   x                                         ",
   "                  x  x  x   x   x  x  x                                         ",
   "                  x  x  x   x   x   x x                                         ",
   "                   xxxxx    x   x    xx                                         ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  @                                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
